### ISSUE TITLE
Cycles light color not exported

### ISSUE THREAD

**Issue by rcorre** [godotengine/godot-blender-exporter#150]
**OS:**

Linux.

**Godot version:**

3.0.6

**Blender version:**

Blender 2.79 (sub 6)
	build hash: 2c0c1f494dcf

**Issue description:**

0. Use cycles render
1. Create a scene with a mesh and point lamp
2. Set the lamp color to something other than white
3. Export to godot
4. Observe that the lamp color is white in Godot.

**Minimal reproduction project:**

![1549232828](https://user-images.githubusercontent.com/2496231/52183749-2bef4b80-27d9-11e9-9821-eb4ab81b2aba.png)
[example.zip](https://github.com/godotengine/godot-blender-exporter/files/2826068/example.zip)

**Comment by rcorre** [comment]
I also get a warning "Ranged light without sphere enabled: Point".
For cycles, I think the check needs to be `size > 0` instead:

> By setting the Size larger than zero, they become spherical lamps, which give softer shadows and shading

https://docs.blender.org/manual/en/latest/render/cycles/lamps.html#point-lamp

**Comment by rcorre** [comment]
Strangely, the following will create a lamp in godot with the correct color:

1. Switch to blender render
2. Add a lamp
3. Switch back to cycles
4. "Convert to Nodes"

However, if I create the lamp in cycles to begin with, the light is always white in godot. The light settings and node view for the two lights (one created in cycles, the other created in blender-render and converted to nodes) they seem the exact same, yet export differently.

[example.zip](https://github.com/godotengine/godot-blender-exporter/files/2826097/example.zip)

**Comment by Jason0214** [comment]
lights in cycle engine is also a shader node tree, now it is not handled.  Convert a cycle light to a godot light shader could be very challenging. Maybe for now it's feasible to just retrieve the color from the shader tree and assign it to light node, then at least, color can be exported.

>Strangely, the following will create a lamp in godot with the correct color:
1.Switch to blender render
2.Add a lamp
3.Switch back to cycles
4."Convert to Nodes"
maybe blender don't delete the previous `blender-engine` light even after convert to cycle light, so that would work.

**Comment by Jason0214** [comment]
done in `master` branch.  May need to do it for `blender2.8` branch as well
