### ISSUE TITLE
installation video please

### ISSUE THREAD

**Issue by kone9** [godotengine/godot-blender-exporter#189]
installation video please!!!!!!!!!!!!!!!!
it does not work on windows 7 64 bits or I do not understand the installation instructions

**Comment by Jason0214** [comment]
sorry for the late response, I had some really busy weeks.

The installation of this addon is almost the same as the [collada-exporter](https://github.com/godotengine/collada-exporter), where we can find [installation procedure](https://github.com/godotengine/collada-exporter#installation). The only thing different is instead of moving `io_scene_dae`, you move `io_scene_godot` from this repo.

Anyway, if you still find it is not very clear, I will try to upload a video when I have time.

**Comment by Jason0214** [comment]
[out.mp4.zip](https://github.com/godotengine/godot-blender-exporter/files/2999018/out.mp4.zip)
