### ISSUE TITLE
Armature which is not an ancestor of Mesh  fails to export

### ISSUE THREAD

**Issue by lee12321** [godotengine/godot-blender-exporter#194]
**OS:**

Windows 10

**Godot version:**

3.1 stable

**Blender version:**

blender-2.80.0-git.790cb7799dcf-windows64

**Issue description:**

error: skip bone fcurves of armature object not being exported.
Animation track not exported correctly, how to avoid the  error?

**Minimal reproduction project:**

**Comment by Jason0214** [comment]
>error: skip bone fcurves of armature object not being exported.

This is a warning arising when some objects have invalid animation data. It would not affect the exported animation, so you can just ignore it.

If you found your exported animation is not correct, could you provide more information?

**Comment by lee12321** [comment]
> If you found your exported animation is not correct, could you provide more information?

I download this file from open game art
[knight.zip](https://github.com/godotengine/godot-blender-exporter/files/2995138/knight.zip)
and after I export it to godot, no animation track is exported

**Comment by Jason0214** [comment]
The issue here is that the Armature of the `Knight` is the sibling of `Knight` mesh. (In usual blender scenes, the Armature Object should be parent of the Mesh Object).
![image](https://user-images.githubusercontent.com/19422835/54871745-a28add00-4d76-11e9-94df-413232760949.png)

Currently the exporter exports blender scene by parsing the scene tree top down breadth first.  In order to support this kind of referencing, it may need to rewrite the main traversal loop to add some smart dependency detection, which could be some big work.

----

As a temporary solution to this issue, just move the `Knight` Mesh to be a child of `Armature`, then everything would be fine.

**Comment by lee12321** [comment]
> As a temporary solution to this issue, just move the `Knight` Mesh to be a child of `Armature`, then everything would be fine.

Tried this quite a few times, find it works well in blender 2.79, in blender 2.8 the animation seems broken in godot.

**Comment by Jason0214** [comment]
@lee12321  I tried it on blender2.8, one thing I notice is that when you open this scene on blender2.8, the `Armature` object is default to be `invisible`, which would cause the animation not exported when the addon's 'Only Visible Object' is checked (which is default).    Other than that, it works fine.

**Comment by Jason0214** [comment]
Note for a compact fixing of this issue:

A simple approach I have thought about is to split the main parsing logic into two passes. In the first pass, build godot scene tree and all the parent/children relations. Then in the second pass, parsing the data of each objects and store in to godot nodes. Finally do serialization.

In this way, this reference to ancestors can be successfully handled

**Comment by Jason0214** [comment]
It is fixed on `blender2.8` branch
