### ISSUE TITLE
¿cómo es el diseño de esté programa?-----how is the design of this program?

### ISSUE THREAD

**Issue by kone9** [godotengine/godot-blender-exporter#2]
Estoy revisando el codigo pero no entiendo mucho cómo es el diseño de este programa, ni como funciona.Alguien tiene un diagrama de flujo de esté programa,tengo poco tiempo con python,pero seria una buena practica tratar de ayudar a desarrollar esté software.

 I am reviewing the code but I do not understand much how is the design of this program, or how it works. Someone has a flow diagram of this program, I have little time with python, but it would be a good practice to try to help develop this software.

![2018-01-30 10_49_49-export_godot py - visual studio code](https://user-images.githubusercontent.com/12847027/35569616-573e21ea-05ab-11e8-82a3-d18acf666a3c.jpg)

**Comment by set-killer** [comment]
Just try to read the code from the bottom to top. The file is not that big, especially when you exclude the commented lines.

**Comment by kone9** [comment]
Ya se que se lee de arriba hacia abajo,pero no entiendo como es el diseño del programa,ni como se relaciona cada función con la api de blender3D.gracias por la sugerencia.

I know it reads from top to bottom, but I do not understand how the program design is, nor how each function relates to the api of blender3D. Thanks for the suggestion.

**Comment by set-killer** [comment]
Well, here the structure is somehow inverted. The most important methods are at the bottom of the file.

The Blender's API is exposed trough the `bpy` module.

**Comment by sdfgeoff** [comment]
Blender's addon API is quite convoluted. But the major flow in this exporter is:
 - The function "save" in export_godot.py
 - It then iterates through each object in the scene in "export" function of the GodotExporter class
 - Inside export_node() it figures out what function handles each type of blender object

From there it devolves into lots of long functions for handling meshes etc, currently with lots of commented out code (in the form of multi-line strings).

But in the end, everything ends up getting dumped into GodotExport.writel() which "stores" the file until the actual write is performed. (This is done because the escn format has three main sections, and you need to wait until you can write the first section before you can start writing the second).

Hopefully this gives you a bit of an idea of how the exporter works.

**Comment by kone9** [comment]
ok,thanks
