### ISSUE TITLE
No texture coordinate input warning and no textures in godot

### ISSUE THREAD

**Issue by Nebulean** [godotengine/godot-blender-exporter#231]
**OS:** Linux

**Godot version:** 3.1.1

**Blender version:** 2.80 RC1

**Issue description:** When trying to export an asset with a normal map, I get the following warning:
`No texture coordinate input for 'ShaderNodeTexImage' UV is used by default, at 'Image Texture'.`
When importing the result into Godot, the asset does not contain the material from Blender.

I am only a beginner, so maybe I made a dumb mistake somewhere, but I can't make it work.
Note that I used the commit `e998175` of godot-blender-exporter (branch blender2.8).

**Minimal reproduction project:**
To reproduce the problem, simply try to export the "lp" object of the attached blender file into any godot project.
[data.zip](https://github.com/godotengine/godot-blender-exporter/files/3408397/data.zip)

Thank you for your help !

**Comment by Jason0214** [comment]
I am not able to reproduce the issue, tested with blender2.80 RC2 build.  Note that the exported material is under lp.Mesh.Surface1.Material, it is not presented in the lp.Material slots.  Anyway, if the exporting works, you are able to see the normal map effect in viewport.

`No texture coordinate input for 'ShaderNodeTexImage' UV is used by default, at 'Image Texture'.` This warning is telling you that because you didn't specify Texture Coordinate input for your NormalMapShaderNode, the 'UV' texture coordinate is used. I see there is a workable UV mapping in your lp object, so you can just ignore this warning message, everything should be fine.

**Comment by Nebulean** [comment]
Thank you very much for you answer.

I tried again with the RC2 of Blender 2.80, but I still have the same problem.

As I understand it, you suggest that my problem is under Godot. I indeed see a material (the good one?) under lp.Mesh.Surface1.Material, but I can't see the effect of normal map or simply any color change in the viewport. Should it be located under lp.Material to affect the viewport ?

I certainly misunderstand something, but I can't make it work.

This is my export settings in blender: 
![Screenshot from 2019-07-21 20-50-20](https://user-images.githubusercontent.com/9269185/61595596-44251c80-abf9-11e9-8193-bb67e75218bf.png)

This is the exported scene: [plan.zip](https://github.com/godotengine/godot-blender-exporter/files/3414930/plan.zip)

And this is what I see in godot: 
![Screenshot from 2019-07-21 20-39-29](https://user-images.githubusercontent.com/9269185/61595507-62d6e380-abf8-11e9-8553-8c0a0b6c21e4.png)

Do you have the same result in godot using this scene ? Is something wrong with my export ?

Thank you again for your help. :)

**Comment by Jason0214** [comment]
I got it exported correct, see
<img width="1426" alt="Screen Shot 2019-07-21 at 12 58 28" src="https://user-images.githubusercontent.com/19422835/61595672-58e0c080-abb7-11e9-90b5-c1f97d0764f5.png">

can you confirm you have seen the normal map effect in Blender?

---

I checked your attached plan.escn, the shader is exported correctly, I think the issue is that Godot is not able to find your texture file.

```
[ext_resource id=1 path="plan normals" type="Texture"]
...
```

Your texture path is 'plan normals' in escn, however I think it may be 'plan normals.png'. Note that we I open your attached .blend file, blender can not find the texture. I did an 'Open Image' to make it right.
![image](https://user-images.githubusercontent.com/19422835/61595720-0bb11e80-abb8-11e9-904a-17884c62dbaa.png)

Maybe you can try the same thing and re-export it to see if it works out.

**Comment by Nebulean** [comment]
First, I confirm that I see the effect of the normal map in blender. This is what I get: 
![Screenshot from 2019-07-21 21-40-43](https://user-images.githubusercontent.com/9269185/61596157-3921ba80-ac00-11e9-9827-4616d9d3dcfc.png)
I changed the 'plan normals' to 'plan normals.png', but the result did not changed.

That said, I see you tested it on macOS, so I also tried on a mac, and guess what ? It worked!

Could my problem be OS related ? I tried again on linux, and it still doesn't work. I reinstall Godot and blender, and it also does not work.

**Comment by Jason0214** [comment]
In that case, I think it's most likely an OS related issue. I will find a Linux platform to investigate it.  Thank you very much for trying!

**Comment by Jason0214** [comment]
Sorry for the late, I can reproduce it on Linux if the used image has no extension name.  Hopefully #239 would fix this issue

**Comment by Nebulean** [comment]
It seems to be working, thank you for your work!
