### ISSUE TITLE
the duplication check of mesh vertices

### ISSUE THREAD

**Issue by Jason0214** [godotengine/godot-blender-exporter#31]
there is a procedure to create a hash for every vertex and check for duplication before serialize them (it creates some trouble for morph exporting),   I wonder why it is needed,  I think the blender mesh.vertices already has no duplicated vertex.

**Comment by sdfgeoff** [comment]
And yet if you analyze the check (~line 205 of `mesh.py`) you'll see that many times (in fact the majority of times) the vertex does not have to be added, but it's index can be retrieved from the existing vertex table.

This is because when extracting the vertices it iterates through face loops. This means that for each face in the mesh, it goes around all three (or more) vertices. This results in duplicated vertices, but it is the only way to get information about split edges (eg sharp edges, different vertex colors on the different faces, non-matching UV's and so on).

**Comment by Jason0214** [comment]
leave comments for other people may have same question: 
In blender mesh.vertices are just a position in 3d space, e.g. it didn't store vertex with same position but different normals twice in mesh.vertices, the normal is handled by loop.  So it is wrong to just export mesh.vertices
