### ISSUE TITLE
Document "_loop" vs "-loop"

### ISSUE THREAD

**Issue by MBetters** [godotengine/godot-blender-exporter#310]
The [docs](https://docs.godotengine.org/en/3.1/getting_started/workflow/assets/importing_scenes.html#animation-loop-loop-cycle) say to use `-loop`, but this add-on currently uses `_loop`. This really tripped me up, so I think the documentation should be updated.

**Comment by fakedeltatime** [comment]
Does -loop not work? The docs say the the action only needs to start or end with the case sensitive prefix or suffix "loop", the hyphen or underscore isn't apparently necessary, although I only found out about this feature and haven't taken advantage of it yet.

**Comment by rcorre** [comment]
The docs you linked are for the [collada-exporter](https://github.com/godotengine/collada-exporter), not this project (the "escn" exporter). The [docs for this](https://docs.godotengine.org/en/3.1/getting_started/workflow/assets/escn_exporter/animation.html) don't mention looping at all, and probably should.

I only added `_loop` because I generally believe having more than one way to do things just causes confusion, but given that the collada exporter already set a precedent, maybe it would be less confusing to support all variations. Thoughts?

**Comment by mysticfall** [comment]
I wonder what could be the significance of godotengine/godot#32678 on this issue.

It looks to me there's a consensus for making the behaviour consistent over different exporters, and there has been some work going on to make other exporters follow the convention.

Maybe we should follow suit, also?

**Comment by Calinou** [comment]
I think the way to go would be to use `-` suffixes, to be consistent with the behavior in the Collada exporters. If a `_` suffix is detected when importing a scene, print an error message telling the user to use a `-` suffix instead. Same goes if uppercase characters are used in the suffix :slightly_smiling_face:
