### ISSUE TITLE
Model broken on export to godot

### ISSUE THREAD

**Issue by thegamerx1** [godotengine/godot-blender-exporter#361]
**OS:**
WIN

**Godot version:**
3.2.2

**Blender version:**
2.82

**Issue description:**
Model broken doesnt happen with gltf or fbx but i need this one becuase the others dont export with emission

**Minimal reproduction project:**
[pistol.zip](https://github.com/godotengine/godot-blender-exporter/files/5162416/pistol.zip)

![untitled](https://user-images.githubusercontent.com/34986564/91986599-6a821a80-ed1c-11ea-95f1-2316a54d84d7.png)
![image](https://user-images.githubusercontent.com/34986564/91986659-7ff74480-ed1c-11ea-91b5-b44fb8ae94fa.png)

**Comment by Calinou** [comment]
Try adding a Triangulate modifier to your mesh in Blender and ensure **Apply Modifiers** is enabled in the Export dialog. (Alternatively, you can enable the Triangulate Faces in the export dialog if there's one.)

**Comment by thegamerx1** [comment]
Theres no Triangulate Faces in the export dialog I tried adding the modifier but it didnt do anything

**Comment by rcorre** [comment]
A face on the right side looked "off" to me. I can't say exactly what was wrong, but I used the `knife` tool to add the edge shown below, and the unexpected face went away in Godot:
![1599475785](https://user-images.githubusercontent.com/2496231/92380203-ba732f80-f0d6-11ea-9fdd-47c068bc54c4.png)

**Comment by scurest** [comment]
The problem is the triangulation calculated by the exporter is not always the one Blender uses. Triangulation is done with

https://github.com/godotengine/godot-blender-exporter/blob/564aa4f56cfe72be2d3c76893fe0380bb7548b8e/io_scene_godot/converters/utils.py#L38-L39

If you manually apply a Triangulate modifier to the pistol and set "Quad Method" to "Fixed Alternate", you'll see the same effect as in Godot. Using "Shortest Diagonal" works in this case though.

Unfortunately none of the options for `quad_method` exactly duplicates the triangulation Blender actually uses. The only way I know of to access this is through `mesh.loop_triangles`. What you really want is a way to say "triangulate this mesh the same way mesh.calc_loop_triangles" does it".
