### ISSUE TITLE
Rigged mesh looks deformed when imported to Godot

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot-blender-exporter#37]
* Version : `master` / 88a8803cd

I tried to import a rigged character to Godot using godot-blender-exporter, but it made some parts of the mesh deformed as shown below:

![deformation](https://user-images.githubusercontent.com/2367032/40892612-5e24ea9e-67d4-11e8-94fa-958e16faff21.png)

The source Blender file that caused the issue can be found in the below link:

* https://github.com/mysticfall/AlleyCat/blob/master/Design/Blender/Characters/Human/Female/Body.blend

**Comment by sdfgeoff** [comment]
Likely linked to #36, but there also seem to be some odd bone positions there.

Initial speculation: the case where bone weight is non-normalized

**Comment by beniwtv** [comment]
I also have a variation of this - not sure if it's the exporter or Godot.

When I import a model that has some vertices not assigned to any bone (like a base stand for a robot arm, for example), I get this problem.

It seems to pull the vertices without bone assignment towards the center (0,0,0) of the scene.

**Comment by sdfgeoff** [comment]
Should be fixed with #44. Blender auto-normalizes bone weights, godot doesn't.

@beniwtv
Vertices without bones in blender are left in the mesh position, and in godot they are moved to [0,0,0].  The solution is to create another bone that simply doesn't move.

This is a godot limitation that can't easily be worked around in the exporter. @Jason0214 
This should probably be noted in the docs.

**Comment by mysticfall** [comment]
I just tested the new version and I can confirm it fixed my probem indeed. Thanks much for the great work! :+1:
