### ISSUE TITLE
Exportation messes up the bone order in godot

### ISSUE THREAD

**Issue by nicolaslanzoni** [godotengine/godot-blender-exporter#385]
**OS:**
Linux(Ubuntu 18.04)

**Godot version:**
3.2.3

**Blender version:**
2.83.3

**Issue description:**
When exporting the script adds the bones according to the creation order, this becomes a problem when reimporting to godot, resulting in the root bone not being the 0 id. This happens if you add the root bone after the others.

I really needed to export my mesh so i forked the repo with what i believe is a decent correction (not a python dev): https://github.com/godotengine/godot-blender-exporter/compare/master...nicolaslanzoni:master

**Comment by nicolaslanzoni** [comment]
#386

**Comment by timjklein36** [comment]
I noticed that certain versions of Blender iterate through the `pose.bones` in a different order than others.

My development machine iterates in hierarchical order matching what is scene in the blender scene tree.

Versions:

**OS:**
Arch Linux (5.11.1)

**Godot version:**
3.2.3

**Blender version:**
2.92.0

My other setup iterates through the `pose.bones` (the same file with the same armature and bone setup) in a different order.

Versions:

**OS:**
Mac OS Sierra

**Godot version:**
3.2.3

**Blender version:**
2.81-a

On the older version, the bones added most recently show up at the end of the iteration, even though they are setup early in the bone hierarchy. 

I would guess (because I had trouble verifying in their source code) that the iteration order code is not consistent between versions of Blender or the Blender Python API.
