### ISSUE TITLE
No file created and blender animation missing after export

### ISSUE THREAD

**Issue by dodgyville** [godotengine/godot-blender-exporter#69]
Hi, I have a sample animation that plays fine in blender but when I use the godot exporter (latest code) the following happens:

1. No escn file is created
2. The animation in blender is now missing
3. There's nothing on the commandline to suggest anything is amiss.
```
[INFO]: Exporting scene: Scene
[INFO]: Exporting 4 objects
[INFO]: Exporting Blender Object: Hips
[INFO]: Exporting Blender Object: Poly_HF_mixamo_export
```
I have attached the file that I import into blender. Happy to help debug if I can.

PS. I'm really impressed with this project!

[HF_low_poly_100frames.fbx.zip](https://github.com/godotengine/godot-blender-exporter/files/2264549/HF_low_poly_100frames.fbx.zip)

**Comment by Jason0214** [comment]
When I open this fbx and export, it reported to me that some vertices are not assigned a bone weight and the exporting failed.
<img width="679" alt="screen shot 2018-08-06 at 19 11 32" src="https://user-images.githubusercontent.com/19422835/43750329-be45cbb4-99ac-11e8-88a9-cd9eb1caa09e.png">
As you said there are nothing in the command line and the animation disappeared (which didn't happen to me), I suppose we are using a different blender version.  May I have the information of which blender version are you use? then I can test more about this issue. Thanks for your support

**Comment by dodgyville** [comment]
2.79b (ubuntu 18.04)

**Comment by Jason0214** [comment]
I am pretty sure your fbx have some bone weights problem,  some vertex has no bone weights assigned (if you wonder why it causes problem, you can take a look at #37),  after I fix the bone weights problem, the blend can be exported successfully  (ignore the deform of mesh, it is caused by my brutal fix of bone weights)
![image](https://user-images.githubusercontent.com/19422835/43805669-848ae6ee-9a55-11e8-8380-0f4becdd727f.png)

I am not sure about what you mean by animation is missing, is the animation data missing?  if it is just the mesh didn't deformed by the bones, you may have a check at the Armature panel, make sure it is set at `Pose Position`
![image](https://user-images.githubusercontent.com/19422835/43805774-ee465c26-9a55-11e8-8884-2340a17eaedc.png)
this button would be set during exporting the mesh and setback when exporting finishes,  but if some Exception raised, it maybe not set back
