### ISSUE TITLE
All nodes are exported as rotated around the x-axis

### ISSUE THREAD

**Issue by Warlaan** [godotengine/godot-blender-exporter#99]
In the exported levels all nodes have a Transform that contains a rotation value of (-90,0,0).

This becomes and issue if you want to animate an object to rotate around the game's z axis due to gimbal lock.

Instead of setting a rotation the coordinates in the mesh data should be exchanged (x becomes z, z becomes-x, if I am not mistaken).

**Comment by Jason0214** [comment]
Yes, currently we are fixing the up axis different in blender and godot by adding a rotation around x-axis.  This suggestion is quite good, I am also thinking about directly applying the rotation into vertex data, and keep the transform matrix same as it was in blender, this also avoids overheads in exported material shader scripts.

For the gimbal lock,  I think you can always stored rotation as quaternion or a matrix to avoid it (correct me if I am wrong).

Anyway, this is a wanted feature, thank you for suggestion.

**Comment by Warlaan** [comment]
The gimbal lock issue happens in the inspector. The rotation of a node is expressed as Euler angles, so if the node starts rotated by 90 degrees there is no linear interpolation of a x-, y- or z-value that expresses a rotation around the world z axis.
You are right though that I could add a (redundant) quaternion as an exported variable and animate that.

I was able to create a workaround by importing the scene with subscenes and then adding a new parent node to the object that was supposed to be animated, but it would of course be nice to have a more straightforward workflow.

Thanks for the reply.

**Comment by Jason0214** [comment]
sorry, I had a bad memory of our implementation of axis fix, my first reply is totally incorrect... 
I checked the code again and I remembered this addon has a fix to every vectors position through 
```
def fix_vertex(vtx):
    """Changes a single position vector from y-up to z-up"""
    return mathutils.Vector((vtx.x, vtx.z, -vtx.y))
``` 
and also swap the up axis of every transform matrix,(if you are curios, see [here](https://github.com/godotengine/godot-blender-exporter/blob/master/io_scene_godot/structures.py#L362))

There is a rotation -90 degree around x axis, but it is not related to transform. You may found the rotation in DirectionalLight or Camera node, it is a direction fix, because in blender these node are default have z-up with identity transform, while in godot they are y-up.  So I think there is nothing to do about it.  If gimbal lock really troubles you, maybe think about recreate the node in godot if it's simple.

**Comment by Jason0214** [comment]
Close for now, if you have more questions, feel free to reopen.
